// SPDX-License-Identifier: Apache-2.0
import fs from 'node:fs';import path from 'node:path';import test from 'node:test';import assert from 'node:assert/strict';import YAML from 'yaml';
import {workspace,write,root} from './helpers/workspace.mjs';import {git} from './helpers/exploration-workflows.mjs';import {setupArchive,finalizeArchive,archiveState,fixtureManifest,binding,checkBinding,safeFile,parse,normalize,operations,preflight,reconcile,verifyArchive,oldLedger,artifact,live,expl,subjectReview,movedReview,ledgerPath,manifestPath,today} from './helpers/archive-workflows.mjs';import {installLocal} from '../scripts/test-install.mjs';import {runProcess} from '../scripts/lib/process.mjs';
const transcript=text=>JSON.stringify({type:'item.completed',item:{type:'agent_message',text}}),clone=x=>JSON.parse(JSON.stringify(x));
function fixture(t,scenario='apply',extra){const p=workspace(t);setupArchive(p,scenario);extra?.(p);return {p,s:finalizeArchive(p,scenario)};}
function manifest(p){return parse(fs.readFileSync(p+'/'+manifestPath,'utf8')).manifest;}
function rewriteManifest(p,change){const m=manifest(p);change(m);write(p,manifestPath,YAML.stringify({manifest:m}));git(p,['add',manifestPath]);git(p,['commit','-qm','Reviewed manifest edit']);return m;}
function candidate(m,tag){const c=clone(oldLedger);c.ledger.updated_at=today();for(const a of m.artifacts.filter(r=>r.disposition==='archive'))c.ledger.records.push({id:a.id,type:a.type==='EXPL'?'exploration':a.type,title:a.id==='EXPL-c333'?'Runtime decision':'Runtime documentation',disposition:a.disposition_class,final_status:a.canonical_status,verified:a.verified,evidence:a.notes,links:{reports:m.reviews.filter(r=>r.action==='delete'&&r.subject===a.id).map(r=>r.path)},source_path:a.path,archive_tag:tag,archived_at:today()});for(const r of m.reviews.filter(r=>r.action==='move-to-archive'))c.ledger.records.push({id:path.basename(r.path,path.extname(r.path)),type:'review',title:'Cross-cutting audit',disposition:'completed',final_status:'completed',verified:'n/a',evidence:'Moved to docs/archive/'+path.basename(r.path),links:{reports:[]},source_path:r.path,archive_tag:tag,archived_at:today()});c.ledger.archives.push({tag,date:today(),count:c.ledger.records.length-oldLedger.ledger.records.length,note:'Fixture archival.'});return c;}
function tagAt(p){const base='idd-archive-'+today().slice(0,7),tags=git(p,['tag','--list']).trim().split('\n');let tag=base,n=2;while(tags.includes(tag))tag=base+'-'+n++;git(p,['tag','-a',tag,'-m','Disposable recovery anchor']);return tag;}
function apply(p,{leaveDirectories=false,lateMismatch=false}={}){const v=preflight(p),tag=tagAt(p),c=candidate(v.manifest,tag);if(lateMismatch)c.ledger.records.pop();write(p,ledgerPath,YAML.stringify(c));reconcile(parse(fs.readFileSync(p+'/'+ledgerPath,'utf8')),oldLedger,v.manifest,tag);for(const rel of v.removed)fs.unlinkSync(p+'/'+rel);if(!leaveDirectories)fs.rmSync(p+'/'+expl,{recursive:true});for(const move of v.moves){fs.mkdirSync(path.dirname(p+'/'+move.to),{recursive:true});fs.renameSync(p+'/'+move.from,p+'/'+move.to);}fs.unlinkSync(p+'/'+manifestPath);git(p,['add','--',ledgerPath,manifestPath,...v.removed,...v.moves.flatMap(m=>[m.from,m.to])]);git(p,['commit','-qm','Apply disposable archive']);return tag;}
function classify(p){const rel='docs/reviews/idd-archive-manifest-'+today()+'-2.yaml',m=fixtureManifest(p,rel).manifest;m.scan_totals={products:1,intentions:2,expectations:3,specs:1,explorations:1,reviews:4};m.artifacts.push({id:'SPEC-d444',path:'docs/specs/SPEC-d444-incomplete.yaml',type:'spec',raw_status:'Done',canonical_status:'done',disposition:'keep',reason:'status-correction',verified:'n/a',flags:[],notes:'src/missing-tool.mjs is absent.'},{id:'EXP-e555',path:'docs/expectations/EXP-e555-obligation.yaml',type:'expectation',raw_status:'deferred',canonical_status:'deferred',disposition:'archive',disposition_class:'deferred',reason:'deferred',verified:'frontmatter',flags:['KEEP-RECOMMENDED?'],notes:'Hard future obligation production blocker.'},{id:'EXP-f666',path:'docs/expectations/EXP-f666-unknown.yaml',type:'expectation',raw_status:'alien-state',canonical_status:'alien-state',disposition:'keep',reason:'status-unknown',flags:['status-unknown'],notes:'Unknown lifecycle.'},{id:'EXP-a777',path:'docs/expectations/EXP-a777-orphan.yaml',type:'expectation',raw_status:'draft',canonical_status:'draft',disposition:'archive',disposition_class:'abandoned',reason:'orphan',verified:'n/a',flags:[],notes:'Unfinished child of completed parent.'});m.orphans=[{id:'EXP-a777',orphaned_by:'INT-a111'}];m.reviews.push({path:'docs/reviews/idd-archive-manifest-'+today()+'.yaml',action:'keep',reason:'Preserve previous manifest.'});m.proposed={archive:4,keep:4};write(p,rel,YAML.stringify({manifest:m}));return rel;}
test('complete disposable apply yields three records and tag byte/mode recovery',t=>{const {p,s}=fixture(t);apply(p);assert.equal(verifyArchive(p,s,transcript('INT-a111 survives as a reference; push with --follow-tags later.')).records,3);});
test('classify preserves original manifest, sources and published review',t=>{const {p,s}=fixture(t,'classify');classify(p);assert.equal(verifyArchive(p,s,transcript('Manifest saved for review.')).outcome,'passed');});
for(const scenario of ['dirty','undistillable'])test('real '+scenario+' preflight refuses without tag/deletion',t=>{const {p,s}=fixture(t,scenario);assert.throws(()=>preflight(p));assert.equal(verifyArchive(p,s,transcript(scenario==='dirty'?'Dirty USER-NOTES.md; refused.':'Cannot parse malformed artifact YAML; refused.')).outcome,'passed');});
test('late persisted-ledger mismatch leaves recovery tag/ledger but deletes nothing',t=>{const {p,s}=fixture(t);assert.throws(()=>apply(p,{lateMismatch:true}),/count/);for(const rel of Object.keys(s.before.entries).filter(p=>s.before.entries[p].kind==='file'&&p!==ledgerPath))assert.equal(fs.readFileSync(p+'/'+rel).length>0,true);assert.ok(git(p,['tag','--list']).trim());assert.ok(fs.existsSync(p+'/'+manifestPath));});
for(const bad of ['../outside','/tmp/outside','docs/../outside','docs//x','docs\\x'])test('unsafe path refused '+bad,t=>{const {p}=fixture(t);assert.throws(()=>safeFile(p,bad));});
for(const kind of ['symlink','hardlink','ancestor'])test('unsafe '+kind+' refused',t=>{const {p}=fixture(t);if(kind==='ancestor'){fs.symlinkSync('docs',p+'/alias');assert.throws(()=>safeFile(p,'alias/idd-ledger.yaml'));}else{const rel='docs/reviews/unsafe.md';if(kind==='symlink')fs.symlinkSync('../idd-ledger.yaml',p+'/'+rel);else fs.linkSync(p+'/'+ledgerPath,p+'/'+rel);assert.throws(()=>safeFile(p,rel));}});
for(const input of ['a: 1\na: 2\n','a: [broken','a: !unknown x','[a,b]'])test('unsafe YAML refused '+input,()=>assert.throws(()=>parse(input)));
for(const [type,raw,value]of[['intention','Complete','fulfilled'],['intention','implemented','fulfilled'],['spec','implemented','done'],['expectation','implemented','done'],['spec','approved','ready'],['spec','InProgress','in-progress'],['expectation','Pending','deferred']])test('in-memory status normalization '+raw,()=>assert.equal(normalize(type,raw),value));
for(const target of ['code','spec','ledger','membership','mode'])test('committed '+target+' changes invalidate reviewed inputs',t=>{const {p}=fixture(t,'apply',p=>{write(p,'src/runtime.mjs','export const runtime = "node";\n');write(p,'docs/specs/SPEC-abcd.yaml','spec: {id: SPEC-abcd, status: draft}\n');});if(target==='membership')write(p,'NEW.md','New bound content.\n');else if(target==='mode')fs.chmodSync(p+'/USER-NOTES.md',0o755);else fs.appendFileSync(p+'/'+({code:'src/runtime.mjs',spec:'docs/specs/SPEC-abcd.yaml',ledger:ledgerPath}[target]),'\n# Committed change.\n');git(p,['add','.']);git(p,['commit','-qm','Changed reviewed inputs']);assert.throws(()=>preflight(p),/Stale/);});
test('unchanged-content commit with reviewed manifest remains valid',t=>{const {p}=fixture(t);git(p,['commit','--allow-empty','-qm','No content change']);assert.equal(preflight(p).A,2);});
test('legacy missing binding cannot apply',t=>{const {p}=fixture(t);rewriteManifest(p,m=>delete m.reviewed_inputs);assert.throws(()=>preflight(p),/Legacy/);});
test('uncommitted manifest cannot apply',t=>{const {p}=fixture(t);fs.appendFileSync(p+'/'+manifestPath,'# Pending review change\n');assert.throws(()=>preflight(p),/Dirty/);});
for(const mutation of ['duplicate-row','wrong-id','wrong-type','unknown-action','subjectless-delete','mixed-subject','wrong-count','duplicate-review','wrong-path'])test('invalid manifest '+mutation+' refused',t=>{const {p}=fixture(t);rewriteManifest(p,m=>{if(mutation==='duplicate-row')m.artifacts.push(clone(m.artifacts[1]));if(mutation==='wrong-id')m.artifacts[1].id='INT-ffff';if(mutation==='wrong-type')m.artifacts[1].type='unknown';if(mutation==='unknown-action')m.reviews[0].action='destroy';if(mutation==='subjectless-delete')delete m.reviews[0].subject;if(mutation==='mixed-subject'){m.artifacts[1].disposition='keep';m.proposed={archive:1,keep:3};}if(mutation==='wrong-count')m.proposed.archive++;if(mutation==='duplicate-review')m.reviews.push(clone(m.reviews[0]));if(mutation==='wrong-path')m.artifacts[1].path='../escape.yaml';});assert.throws(()=>preflight(p));});
for(const extra of ['untracked','ignored','symlink'])test('unsafe Exploration '+extra+' member refused',t=>{const {p}=fixture(t);if(extra==='ignored'){write(p,'.gitignore','docs/explorations/**/ignored.txt\n');git(p,['add','.gitignore']);git(p,['commit','-qm','Ignore fixture asset']);rewriteManifest(p,m=>m.reviewed_inputs=binding(p,manifestPath));write(p,expl+'/ignored.txt','Ignored extra.');}else if(extra==='symlink')fs.symlinkSync('map.md',p+'/'+expl+'/unsafe');else write(p,expl+'/untracked.txt','Untracked extra.');assert.throws(()=>preflight(p));});
test('occupied move destination refuses',t=>{const {p}=fixture(t);write(p,'docs/archive/'+path.basename(movedReview),'Existing archive.');git(p,['add','.']);git(p,['commit','-qm','Occupied target']);rewriteManifest(p,m=>m.reviewed_inputs=binding(p,manifestPath));assert.throws(()=>preflight(p),/Occupied/);});
test('existing tag preserved and fresh numeric suffix used',t=>{const {p,s}=fixture(t);const base=tagAt(p),baseHash=git(p,['rev-parse',base]);const state=archiveState(p,'apply');assert.equal(apply(p),base+'-2');assert.equal(git(p,['rev-parse',base]),baseHash);assert.equal(verifyArchive(p,state,transcript('INT-a111 reference; --follow-tags.')).outcome,'passed');});
test('failed tag operation cannot produce successful apply evidence',t=>{const {p,s}=fixture(t);git(p,['tag','occupied']);assert.throws(()=>git(p,['tag','-a','occupied','-m','must fail']));assert.ok(fs.existsSync(p+'/'+artifact));assert.throws(()=>verifyArchive(p,s,transcript('Tag failed; --follow-tags INT-a111.')));});
for(const mutation of ['old-record','old-entry','old-metadata','count','missing-record','duplicate-record','wrong-source','empty-evidence','subject-attribution','review-id'])test('ledger reconciliation rejects '+mutation,t=>{const {p}=fixture(t),m=manifest(p),tag='idd-archive-2026-09',c=candidate(m,tag),r=c.ledger.records;if(mutation==='old-record')r[0].custom='changed';if(mutation==='old-entry')c.ledger.archives[0].note='changed';if(mutation==='old-metadata')c.ledger.custom_metadata='changed';if(mutation==='count')c.ledger.archives.at(-1).count=2;if(mutation==='missing-record')r.pop();if(mutation==='duplicate-record')r[2]=clone(r[1]);if(mutation==='wrong-source')r[1].source_path=live;if(mutation==='empty-evidence')r[1].evidence='';if(mutation==='subject-attribution')r[1].links.reports=[];if(mutation==='review-id')r.at(-1).id='wrong';assert.throws(()=>reconcile(c,oldLedger,m,tag));});
test('co-deleted review attributed to every duplicate-ID variant',t=>{const {p}=fixture(t),m=manifest(p);const variant=clone(m.artifacts[1]);variant.path='docs/intentions/INT-a111-variant.yaml';m.artifacts.push(variant);m.proposed.archive++;const c=candidate(m,'tag');assert.equal(reconcile(c,oldLedger,m,'tag'),4);c.ledger.records.at(-2).links.reports=[];assert.throws(()=>reconcile(c,oldLedger,m,'tag'),/attribution/);});
for(const mutation of ['live-survivor','old-status','unowned-output','left-directory','lightweight-tag'])test('final apply oracle rejects '+mutation,t=>{const {p,s}=fixture(t);const tag=apply(p,{leaveDirectories:mutation==='left-directory'});if(mutation==='live-survivor')fs.appendFileSync(p+'/'+live,'# bad rewrite\n');if(mutation==='old-status')fs.writeFileSync(p+'/'+live,fs.readFileSync(p+'/'+live,'utf8').replace('in-progress','archived'));if(mutation==='unowned-output')write(p,'UNOWNED.md','Bad output.');if(mutation==='lightweight-tag'){git(p,['tag','-d',tag]);git(p,['tag',tag,s.git.head.trim()]);}assert.throws(()=>verifyArchive(p,s,transcript('INT-a111 reference; --follow-tags.')));});
for(const mutation of ['wrong-path','wrong-type','live-archive','missing-review','published-delete','missing-binding'])test('classification oracle rejects '+mutation,t=>{const {p,s}=fixture(t,'classify'),rel=classify(p),v=parse(fs.readFileSync(p+'/'+rel,'utf8'));const m=v.manifest;if(mutation==='wrong-path')m.artifacts[1].path=live;if(mutation==='wrong-type')m.artifacts[1].type='spec';if(mutation==='live-archive')m.artifacts[2].disposition='archive';if(mutation==='missing-review')m.reviews.shift();if(mutation==='published-delete')m.reviews.find(r=>r.path==='docs/reviews/published-evidence.md').action='delete';if(mutation==='missing-binding')delete m.reviewed_inputs;write(p,rel,YAML.stringify(v));assert.throws(()=>verifyArchive(p,s,transcript('Manifest saved.')));});
for(const scenario of ['dirty','undistillable'])test('missing parser is blocked, not valid '+scenario+' refusal',t=>{const {p,s}=fixture(t,scenario);assert.throws(()=>verifyArchive(p,s,transcript('Parser unavailable; malformed or dirty inputs unknown.')),e=>e.code==='HOST_BLOCKED');});
for(const agent of ['codex','claude-code'])for(const copy of [false,true])test('archive alone '+agent+' '+(copy?'copy':'symlink')+' runs scan without hierarchy creation',t=>{const p=workspace(t),source=p+'/source',target=p+'/target';fs.cpSync(root+'/plugin/skills/idd-archive',source,{recursive:true});fs.mkdirSync(target);installLocal(source,target,'idd-archive',{copy,stateRoot:p,agents:[agent]});if(copy)fs.rmSync(source,{recursive:true});const skill=target+'/'+(agent==='codex'?'.agents':'.claude')+'/skills/idd-archive';assert.match(runProcess('bash',[skill+'/scripts/idd-archive-scan'],{cwd:target}),/== INVENTORY ==/);assert.equal(fs.existsSync(target+'/docs'),false);});

test('binary Exploration asset recovers exact non-UTF8 bytes',t=>{const {p,s}=fixture(t);apply(p);assert.equal(verifyArchive(p,s,transcript('INT-a111 reference; --follow-tags.')).outcome,'passed');});
for(const mode of ['dangling-target','symlink-parent'])test('move destination rejects '+mode,t=>{const {p}=fixture(t);if(mode==='symlink-parent'){fs.mkdirSync(p+'/outside');fs.symlinkSync('../outside',p+'/docs/archive');}else{fs.mkdirSync(p+'/docs/archive');fs.symlinkSync('missing',p+'/docs/archive/'+path.basename(movedReview));}assert.throws(()=>operations(p,manifest(p)),/Unsafe|Occupied/);});
test('published review remains protected even with invented archived subject',t=>{const {p}=fixture(t),m=manifest(p);Object.assign(m.reviews.find(r=>r.path==='docs/reviews/published-evidence.md'),{action:'delete',subject:'INT-a111'});assert.throws(()=>operations(p,m),/Published/);});
test('documented minimal moved review record needs no invented final_status or verified',t=>{const {p}=fixture(t),m=manifest(p),c=candidate(m,'tag');delete c.ledger.records.at(-1).final_status;delete c.ledger.records.at(-1).verified;assert.equal(reconcile(c,oldLedger,m,'tag'),3);});
for(const mutation of ['missing-resolution','missing-destination','missing-scope','wrong-verified'])test('ledger evidence rejects '+mutation,t=>{const {p}=fixture(t),m=manifest(p),c=candidate(m,'tag'),r=c.ledger.records.find(r=>r.id==='EXPL-c333');if(mutation==='wrong-verified')r.verified='invented';else r.evidence=r.evidence.replace({'missing-resolution':'Node.js 22.20.0 or newer','missing-destination':'tooling migration','missing-scope':'deployment policy'}[mutation],'unknown');assert.throws(()=>reconcile(c,oldLedger,m,'tag'));});
test('valid numeric recovery tag suffix ten is accepted',t=>{const {p}=fixture(t);for(let n=0;n<9;n++)tagAt(p);const s=archiveState(p,'apply');assert.ok(apply(p).endsWith('-10'));assert.equal(verifyArchive(p,s,transcript('INT-a111 reference; --follow-tags.')).outcome,'passed');});
for(const mutation of ['deleted','moved'])test('existing tag '+mutation+' rejected',t=>{const {p}=fixture(t);git(p,['tag','historical']);const s=archiveState(p,'apply');apply(p);git(p,['tag','-d','historical']);if(mutation==='moved')git(p,['tag','historical']);assert.throws(()=>verifyArchive(p,s,transcript('INT-a111 reference; --follow-tags.')),/Existing tag changed/);});
test('status-correction flag placement accepted',t=>{const {p,s}=fixture(t,'classify'),rel=classify(p),v=parse(fs.readFileSync(p+'/'+rel,'utf8')),r=v.manifest.artifacts.find(r=>r.id==='SPEC-d444');r.reason='Partial code check';r.flags=['status-correction'];write(p,rel,YAML.stringify(v));assert.equal(verifyArchive(p,s,transcript('Manifest saved.')).outcome,'passed');});

test('non-Git-recoverable permission mode refuses instead of claiming lossless recovery',t=>{const {p}=fixture(t);fs.chmodSync(p+'/'+expl+'/assets/sample.bin',0o600);rewriteManifest(p,m=>m.reviewed_inputs=binding(p,manifestPath));assert.throws(()=>preflight(p),/permission mode/);});

for(const mutation of ['disposition-class','verified','orphan-parent','manifest-date'])test('classification exact contract rejects '+mutation,t=>{const {p,s}=fixture(t,'classify'),rel=classify(p),v=parse(fs.readFileSync(p+'/'+rel,'utf8'));if(mutation==='disposition-class')v.manifest.artifacts[1].disposition_class='abandoned';if(mutation==='verified')v.manifest.artifacts[1].verified='code';if(mutation==='orphan-parent')v.manifest.orphans[0].orphaned_by='INT-b222';if(mutation==='manifest-date')v.manifest.date='1999-01-01';write(p,rel,YAML.stringify(v));assert.throws(()=>verifyArchive(p,s,transcript('Manifest saved.')));});
for(const scenario of ['classify','apply'])test('hardlinked owned '+scenario+' output rejected',t=>{const {p,s}=fixture(t,scenario);let output;if(scenario==='classify')output=classify(p);else{apply(p);output=ledgerPath;}const external=workspace(t);fs.linkSync(p+'/'+output,external+'/alias');assert.throws(()=>verifyArchive(p,s,transcript('Manifest INT-a111 --follow-tags.')),/Hardlinked/);});
test('preserved 0600 user file does not block recoverable selected paths',t=>{const {p}=fixture(t,'apply',p=>write(p,'PRIVATE-NOTES.md','Private local note.\n',0o600));assert.equal(preflight(p).A,2);});
test('unsupported manifest mode refuses without changing it',t=>{const {p}=fixture(t);fs.chmodSync(p+'/'+manifestPath,0o600);assert.throws(()=>preflight(p),/permission mode/);assert.equal(fs.statSync(p+'/'+manifestPath).mode&0o777,0o600);});

test('classify accepts either Git-recoverable new manifest mode',t=>{const {p,s}=fixture(t,'classify'),rel=classify(p);fs.chmodSync(p+'/'+rel,0o755);assert.equal(verifyArchive(p,s,transcript('Manifest saved.')).outcome,'passed');fs.chmodSync(p+'/'+rel,0o600);assert.throws(()=>verifyArchive(p,s,transcript('Manifest saved.')),/Manifest mode/);});

test('unknown canonical null and additive orphan provenance retain strict identity',t=>{const {p,s}=fixture(t,'classify'),rel=classify(p),v=parse(fs.readFileSync(p+'/'+rel,'utf8'));v.manifest.artifacts.find(r=>r.id==='EXP-f666').canonical_status=null;v.manifest.orphans[0].path='docs/expectations/EXP-a777-orphan.yaml';write(p,rel,YAML.stringify(v));assert.equal(verifyArchive(p,s,transcript('Manifest saved.')).outcome,'passed');});


test('optional Claude evaluation effort preserves configured model and default invocation', async()=>{
  const {archiveInvocation}=await import('../scripts/evaluate-archive.mjs');
  const standard=archiveInvocation('claude','prompt','/tmp');
  const bounded=archiveInvocation('claude','prompt','/tmp','medium');
  assert.deepEqual(bounded,{...standard,args:[...standard.args,'--effort','medium']});
  assert.equal(standard.args.includes('--model'),false);
  assert.equal(standard.args.includes('--effort'),false);
  assert.throws(()=>archiveInvocation('codex','prompt','/tmp','medium'),/requires Claude/);
});
test('evaluation options reject unsupported or ambiguous effort before fixture creation', async()=>{
  const {parseArchiveOptions}=await import('../scripts/evaluate-archive.mjs');
  assert.deepEqual(parseArchiveOptions(['--host','claude','--scenario','apply','--claude-effort','medium']),{host:'claude',scenario:'apply',claudeEffort:'medium'});
  for(const args of [ ['--host','claude','--scenario','apply','--claude-effort','max'],['--host','codex','--scenario','apply','--claude-effort','medium'],['--host','claude','--scenario','apply','--claude-effort'],['--host','claude','--scenario','apply','--host','claude'] ])assert.throws(()=>parseArchiveOptions(args));
});


test('long evaluation allowance is restricted to explicitly selected Claude apply',async()=>{
  const {evaluationTimeout,parseArchiveOptions}=await import('../scripts/evaluate-archive.mjs');
  for(const host of ['claude','codex'])for(const scenario of ['apply','classify','dirty','undistillable'])assert.equal(evaluationTimeout(host,scenario),600);
  assert.equal(evaluationTimeout('claude','apply',1200),1200);
  assert.equal(parseArchiveOptions(['--host','claude','--scenario','apply','--timeout-seconds','1200']).timeoutSeconds,1200);
  for(const [host,scenario,seconds] of [['codex','apply',1200],['claude','dirty',1200],['claude','classify',1200],['claude','undistillable',1200],['claude','apply',900],['claude','apply',0],['claude','apply',NaN],['claude','apply',Infinity],['claude','apply','1200']])assert.throws(()=>evaluationTimeout(host,scenario,seconds));
});
test('CLI rejects invalid evaluation time before any fixture work',async()=>{
  const {parseArchiveOptions}=await import('../scripts/evaluate-archive.mjs');
  for(const args of [['--host','codex','--scenario','apply','--timeout-seconds','1200'],['--host','claude','--scenario','apply','--timeout-seconds','bad'],['--host','claude','--scenario','classify','--timeout-seconds','1200'],['--host','claude','--scenario','apply','--timeout-seconds']])assert.throws(()=>parseArchiveOptions(args));
});
test('low effort is explicit Claude-only evaluation without model/style overrides',async()=>{const {archiveInvocation,parseArchiveOptions}=await import('../scripts/evaluate-archive.mjs');const standard=archiveInvocation('claude','prompt','/tmp');assert.deepEqual(archiveInvocation('claude','prompt','/tmp','low'),{...standard,args:[...standard.args,'--effort','low']});assert.throws(()=>archiveInvocation('codex','prompt','/tmp','low'));assert.equal(parseArchiveOptions(['--host','claude','--scenario','apply','--claude-effort','low','--timeout-seconds','1200']).claudeEffort,'low');});
