// SPDX-License-Identifier: Apache-2.0
// These tests exercise the acceptance oracle, not model reasoning or a production writer.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import YAML from 'yaml';
import {workspace,write,root} from './helpers/workspace.mjs';
import {setupAuthoring,verifyAuthoring,authoringPrompt,stages,facts,intentionFile,productFile,expectationFile,verifyConcurrentOutcome} from './helpers/authoring.mjs';
import {snapshot,hash} from '../plugin/runtime/snapshot.mjs';
const response=text=>JSON.stringify({type:'item.completed',item:{type:'agent_message',text}});
function proposal(project,state) {
  const ids={intention:'INT-f00d',expectation:'EXP-f00d',spec:'SPEC-f00d'},i={id:ids.intention,product:'PROD-a1b2',statement:facts.statement,rationale:facts.rationale,priority:'medium',dependencies:[],expectations:state.stage==='define-intentions'?[]:[ids.expectation],owner:facts.owner,status:'draft',exploration:'EXPL-cafe'};
  const e={id:ids.expectation,intention:state.stage==='define-expectations'?'INT-a1b2':ids.intention,description:facts.description,validation_criteria:facts.validation,edge_cases:facts.edges,complexity:'low',owner:facts.owner,status:'draft',exploration:'EXPL-cafe'};
  const multi=state.variant==='multi-intention-spec',selected=state.stage==='write-spec'?(multi?['EXP-a1b2','EXP-b2c3']:['EXP-a1b2']):[e.id],parents=state.stage==='write-spec'?(multi?['INT-a1b2','INT-b2c3']:['INT-a1b2']):[i.id];
  const s={id:ids.spec,product:'PROD-a1b2',intentions:parents,expectations:selected,status:'draft',context:{stack:'Node 22 ESM',patterns:'Pure functions',conventions:['Use named exports'],auth:'None',existing_code_refs:[{path:'package.json',note:'Existing package'}]},expectations_detail:selected.map(id=>({id,description:facts.description,validation:facts.validation,edge_cases:facts.edges})),boundaries:facts.boundaries,deliverables:facts.deliverables,validation:{automated:facts.automated,human_review:facts.human_review},exploration:'EXPL-cafe'};
  const kinds=state.stage==='define-intentions'?['intention']:state.stage==='define-expectations'?['expectation']:state.stage==='define-outcomes'?['intention','expectation']:state.stage==='quick-spec'?['intention','expectation','spec']:['spec'];const all={intention:i,expectation:e,spec:s};
  for(const kind of kinds){const value=all[kind];if(state.variant==='absent-lineage')delete value.exploration;write(project,`docs/${kind==='spec'?'specs':kind+'s'}/${value.id}.yaml`,YAML.stringify({[kind]:value}));}
  if(state.stage==='define-expectations'){const f=path.join(project,intentionFile);fs.writeFileSync(f,fs.readFileSync(f,'utf8').replace('expectations: []','expectations: [EXP-f00d]'));}
}
for(const stage of stages)test(`oracle accepts exact ${stage} outputs`,t=>{const project=workspace(t),state=setupAuthoring(project,stage);proposal(project,state);assert.equal(verifyAuthoring(project,state,response('Saved the confirmed draft artifacts.')).outcome,'passed');});
for(const [stage,variant]of [['define-intentions','absent-lineage'],['write-spec','multi-intention-spec']])test(`oracle handles ${variant}`,t=>{const project=workspace(t),state=setupAuthoring(project,stage,variant);proposal(project,state);assert.equal(verifyAuthoring(project,state,response('Saved confirmed drafts.')).outcome,'passed');});
for(const [variant,text]of Object.entries({'missing-confirmation':'Please confirm these two edge cases?\n1. Padding is trimmed, unlike a plain name.\n2. Null throws instead of greeting.','rejected-edge':'We need at least 2 edge cases. Please confirm a replacement?','accelerated-rejected-edge':'We need at least 2 edge cases. Please confirm a replacement?','parent-conflict':'Different Product parents PROD-a1b2 and PROD-beef conflict; which should I use?','lineage-conflict':'Exploration lineage EXPL-cafe and EXPL-feed conflicts; which one should I use?','malformed-parent':'Duplicate YAML key; please repair.','empty-selection':'Which Product should I select: PROD-a1b2 or PROD-beef?','ambiguous-identity':'Duplicate PROD-a1b2 internal IDs; please repair ambiguity.','archived-parent':'Selected PROD-a1b2 parent is archived; should we recover it?'}))test(`oracle requires preservation and meaningful ${variant} response`,t=>{const stage=variant.includes('conflict')?'write-spec':['missing-confirmation','rejected-edge'].includes(variant)?'define-expectations':variant==='accelerated-rejected-edge'?'quick-spec':'define-intentions',project=workspace(t),state=setupAuthoring(project,stage,variant);assert.equal(verifyAuthoring(project,state,response(text)).outcome,'passed');assert.throws(()=>verifyAuthoring(project,state,response('Service unavailable.')));write(project,'unexpected.txt','bad');assert.throws(()=>verifyAuthoring(project,state,response(text)),/wrote project/);});
for(const stage of ['define-outcomes','quick-spec'])test(`oracle rejects ${stage} intermediate save before replacement confirmation`,t=>{const project=workspace(t),state=setupAuthoring(project,stage,'accelerated-rejected-edge');proposal(project,{...state,stage:'define-intentions'});assert.throws(()=>verifyAuthoring(project,state,response('Please confirm a replacement?')),/wrote project/);});
for(const violation of ['duplicate-yaml','status','owner','edges','links','lineage','parent-reformat','unowned','reserved-id','spec-owner'])test(`oracle rejects ${violation}`,t=>{const stage=violation==='spec-owner'?'write-spec':'define-expectations',project=workspace(t),state=setupAuthoring(project,stage);proposal(project,state);const file=path.join(project,stage==='write-spec'?'docs/specs/SPEC-f00d.yaml':'docs/expectations/EXP-f00d.yaml');if(violation==='duplicate-yaml')fs.appendFileSync(file,'  status: ready\n');else if(violation==='parent-reformat'){const p=path.join(project,intentionFile);fs.writeFileSync(p,YAML.stringify(YAML.parse(fs.readFileSync(p,'utf8'))));}else if(violation==='unowned')fs.appendFileSync(path.join(project,'USER-NOTES.md'),'wrong');else {const d=YAML.parse(fs.readFileSync(file,'utf8')),v=d.expectation??d.spec;if(violation==='status')v.status='ready';if(violation==='owner')v.owner='Invented Person';if(violation==='edges')v.edge_cases=[facts.edges[0]];if(violation==='links')v.intention='INT-dead';if(violation==='lineage')v.exploration='';if(violation==='reserved-id')v.id='EXP-dead';if(violation==='spec-owner')v.owner=facts.owner;fs.writeFileSync(file,YAML.stringify(d));}assert.throws(()=>verifyAuthoring(project,state,response('Saved drafts.')));});
for(const variant of ['partial-recovery','already-linked'])test(`recovery oracle reuses existing child and verifies ${variant}`,t=>{const project=workspace(t),state=setupAuthoring(project,'define-expectations',variant);if(variant==='partial-recovery'){const p=path.join(project,intentionFile);fs.writeFileSync(p,fs.readFileSync(p,'utf8').replace('expectations: []','expectations: [EXP-b2c3]'));}assert.equal(verifyAuthoring(project,state,response('Recovered existing child link; no new child.')).outcome,'passed');});
test('prompts keep confirmation variants explicit and configured model unchanged',()=>{for(const stage of stages){assert.match(authoringPrompt(stage,'happy','/installed/SKILL.md'),/configured model/);assert.match(authoringPrompt(stage,'happy','/installed/SKILL.md'),/not human peer review/);}assert.match(authoringPrompt('quick-spec','accelerated-rejected-edge','/installed/SKILL.md'),/Do not assume/);});
test('five bundles preserve their exact resource closure and helper modes',()=>{const catalog=JSON.parse(fs.readFileSync(path.join(root,'plugin/skill-catalog.json')));for(const stage of stages){const b=catalog.bundles.find(b=>b.directory==='idd-'+stage);assert.ok(b);for(const f of b.files){const target=path.join(root,'plugin/skills',b.directory,f.destination);assert.deepEqual(fs.readFileSync(target),fs.readFileSync(path.join(root,f.source)));assert.equal(fs.statSync(target).mode&0o777,f.executable?0o755:0o644);}}});

for(const [variant,message] of [['missing-confirmation','Cannot confirm anything because authentication is unavailable.'],['accelerated-rejected-edge','Please contact support to replace the expired API credential.'],['malformed-parent','YAML tooling cannot be loaded because the host service is unavailable.']])test(`operational error cannot pass ${variant}`,t=>{const project=workspace(t),stage=variant==='missing-confirmation'?'define-expectations':variant==='accelerated-rejected-edge'?'quick-spec':'define-intentions',state=setupAuthoring(project,stage,variant);assert.throws(()=>verifyAuthoring(project,state,response(message)));});

test('oracle rejects negated confirmed facts even when keywords match',t=>{const project=workspace(t),state=setupAuthoring(project,'define-expectations');proposal(project,state);const p=path.join(project,'docs/expectations/EXP-f00d.yaml'),d=YAML.parse(fs.readFileSync(p,'utf8'));d.expectation.description='Never return Hello for a trimmed name; never throw TypeError.';d.expectation.validation_criteria='Ada and empty and null must NEVER throw TypeError.';fs.writeFileSync(p,YAML.stringify(d));assert.throws(()=>verifyAuthoring(project,state,response('Saved drafts.')));});
for(const phase of ['preflight','late'])test(`concurrency outcome oracle verifies ${phase} preservation and exact partial report`,t=>{
  const project=workspace(t),state=setupAuthoring(project,'define-expectations'),parent=path.join(project,intentionFile),original=fs.readFileSync(parent,'utf8'),child='docs/expectations/EXP-b2c3-partial.yaml';
  const candidate=YAML.stringify({expectation:{id:'EXP-b2c3',intention:'INT-a1b2',description:facts.description,validation_criteria:facts.validation,edge_cases:facts.edges,complexity:'low',owner:facts.owner,status:'draft'}});
  // Inject the external edit at the declared boundary. We verify final state, not a writer.
  if(phase==='late')write(project,child,candidate);fs.appendFileSync(parent,'  concurrent_note: preserve me\n');
  const actual=snapshot(project,{excludeGit:true}),interference={...state.before,entries:{...state.before.entries,[intentionFile]:actual.entries[intentionFile]}};
  const report={reason:'parent-changed',parent:intentionFile,written:phase==='late'?[{path:child,id:'EXP-b2c3'}]:[],remaining:phase==='late'?[{path:intentionFile,operation:'append-expectation',id:'EXP-b2c3'}]:[{path:child,operation:'create',id:'EXP-b2c3'},{path:intentionFile,operation:'append-expectation',id:'EXP-b2c3'}]};
  const options={phase,interference,child,id:'EXP-b2c3',candidate,report};assert.equal(verifyConcurrentOutcome(project,options),true);
  for(const altered of [{...report,written:[]},{...report,remaining:[]},{...report,reason:'complete'},{...report,written:[{path:child,id:'EXP-wrong'}]}])if(JSON.stringify(altered)!==JSON.stringify(report))assert.throws(()=>verifyConcurrentOutcome(project,{...options,report:altered}));
  assert.throws(()=>verifyConcurrentOutcome(project,{...options,report:null}));
  fs.writeFileSync(parent,original);assert.throws(()=>verifyConcurrentOutcome(project,options));fs.writeFileSync(parent,original+'  concurrent_note: preserve me\n');
  write(project,'unexpected.txt','bad');assert.throws(()=>verifyConcurrentOutcome(project,options));fs.unlinkSync(path.join(project,'unexpected.txt'));
  if(phase==='late'){fs.unlinkSync(path.join(project,child));assert.throws(()=>verifyConcurrentOutcome(project,options));}
});

for(const filename of ['EXP-f00d.yaml','EXP-f00d-greeting-validation.yaml'])test(`filename oracle accepts ${filename}`,t=>{const project=workspace(t),state=setupAuthoring(project,'define-expectations');proposal(project,state);const old=path.join(project,'docs/expectations/EXP-f00d.yaml');if(!old.endsWith(filename))fs.renameSync(old,path.join(project,'docs/expectations',filename));assert.equal(verifyAuthoring(project,state,response('Saved draft.')).outcome,'passed');});
for(const filename of ['EXP-beef.yaml','EXP-f00-greeting.yaml','EXP-f00d-.yaml','EXP-f00d-Bad.yaml','EXP-f00d-bad--slug.yaml','../intentions/EXP-f00d.yaml'])test(`filename oracle rejects ${filename}`,t=>{const project=workspace(t),state=setupAuthoring(project,'define-expectations');proposal(project,state);fs.renameSync(path.join(project,'docs/expectations/EXP-f00d.yaml'),path.join(project,'docs/expectations',filename));assert.throws(()=>verifyAuthoring(project,state,response('Saved draft.')));});

test('replacement oracle recognizes needs 2 as an explicit minimum',t=>{const project=workspace(t),state=setupAuthoring(project,'define-outcomes','accelerated-rejected-edge');assert.equal(verifyAuthoring(project,state,response('The Expectation needs 2 confirmed edge cases. Please confirm a replacement?')).outcome,'passed');});

test('confirmation oracle accepts a concrete candidate table',t=>{const project=workspace(t),state=setupAuthoring(project,'define-expectations','missing-confirmation');const message='Please confirm these edge cases?\n| Case | Expected | Difference |\n|---|---|---|\n| Padding | Trim padding | Unlike plain name |\n| Null | Throw TypeError | Unlike a string |';assert.equal(verifyAuthoring(project,state,response(message)).outcome,'passed');});

test('replacement oracle accepts singular edge with an explicit two minimum',t=>{const project=workspace(t),state=setupAuthoring(project,'quick-spec','accelerated-rejected-edge');assert.equal(verifyAuthoring(project,state,response('Do you confirm this replacement? One edge is confirmed; at least two are required. Nothing saved.')).outcome,'passed');});
