// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {workspace,write} from './helpers/workspace.mjs';
import {setupExploration,explorationState,verifyExploration,parseMarkdown,frontier,isClear,researchProposal,prototypePath,assertUnresolvedHuman,verifyPartial,assertTaskScope,preservedText,git,expl,ticket,second,fact,question,mapText,ticketText} from './helpers/exploration-workflows.mjs';
const transcript=text=>JSON.stringify({type:'item.completed',item:{type:'agent_message',text}});
const copy=x=>JSON.parse(JSON.stringify(x));
function claim(project,{unrestricted=false}={}){const p=project+'/'+ticket,t=fs.readFileSync(p,'utf8').replace('status: open','status: claimed').replace('claimed_by:','claimed_by: agent-session');fs.writeFileSync(p,t);if(unrestricted){git(project,['add',ticket]);git(project,['commit','-qm','Bad broad claim']);}else git(project,['commit','--only','-qm','Claim selected ticket','--',ticket]);}
function resolveTask(project){claim(project);const p=project+'/'+ticket;fs.writeFileSync(p,fs.readFileSync(p,'utf8').replace('status: claimed','status: resolved').replace('<!-- Preserve resolution comment. -->','<!-- Preserve resolution comment. -->\n\nFACTS.md states '+fact+'.'));const m=project+'/'+expl+'/map.md';fs.writeFileSync(m,fs.readFileSync(m,'utf8').replace('<!-- Existing decision index; preserve this comment. -->','<!-- Existing decision index; preserve this comment. -->\n\n- [Runtime](tickets/01-runtime.md) — Supported runtime confirmed.'));}
function chart(project){const directory='docs/explorations/EXPL-bbbb-runtime';write(project,directory+'/map.md',mapText('EXPL-bbbb').replace('Use local factual evidence. Preserve this note.','Use local factual evidence.').replace('<!-- No remaining vague fog. -->','Long-term adoption approach is not yet specified.').replace('<!-- Existing decision index; preserve this comment. -->','- [Runtime](tickets/01-runtime.md) — Supported runtime confirmed.'));write(project,directory+'/tickets/01-runtime.md',ticketText('research').replace('status: open','status: resolved').replace('MISSING.md','FACTS.md').replace('<!-- Preserve resolution comment. -->','FACTS.md states '+fact+'.'));write(project,directory+'/tickets/02-decision.md',ticketText('grilling'));return directory;}
test('actual fixture task claim excludes staged note and preserves its further worktree edit',t=>{const p=workspace(t),s=setupExploration(p,'task');resolveTask(p);assert.equal(verifyExploration(p,s,transcript('One task resolved.' )).outcome,'passed');});
test('saved JSON baseline retains task claim acceptance',t=>{const p=workspace(t),s=copy(setupExploration(p,'task'));resolveTask(p);assert.equal(verifyExploration(p,s,transcript('One task resolved.')).outcome,'passed');});
test('grilling claim waits for exactly one actual answer',t=>{const p=workspace(t),s=setupExploration(p,'hitl');claim(p);assert.equal(verifyExploration(p,s,transcript(question)).outcome,'passed');});
test('missing persisted research source keeps committed claim/no gist',t=>{const p=workspace(t),s=setupExploration(p,'research-failure');claim(p);assert.equal(verifyExploration(p,s,transcript('MISSING.md is absent; research remains unresolved.')).outcome,'passed');});
for(const scenario of ['no-fog','blocked'])test('no-write '+scenario,t=>{const p=workspace(t),s=setupExploration(p,scenario);assert.equal(verifyExploration(p,s,transcript(scenario==='no-fog'?'Continue with idd-quick-spec.':'Cyclic dependencies block the named ticket.')).outcome,'passed');write(p,'UNOWNED.txt','bad');assert.throws(()=>verifyExploration(p,s,transcript('idd-quick-spec blocked')),/mutated/);});
test('chart factual proposal publishes resolved without fabricated claim/commit',t=>{const p=workspace(t),s=setupExploration(p,'chart');chart(p);assert.equal(verifyExploration(p,s,transcript('Map saved; grilling remains open.')).outcome,'passed');});
for(const status of ['open','claimed'])test('empty frontier with '+status+' ticket cannot clear',()=>{const tickets={'01-q.md':{status,claimed_by:status==='claimed'?'someone':null,blocked_by:['missing.md']}};assert.deepEqual(frontier(tickets),[]);assert.equal(isClear('<!-- empty -->',tickets),false);});
test('cycles and missing dependencies are excluded from frontier',()=>{const tickets={a:{status:'open',blocked_by:['b']},b:{status:'open',blocked_by:['a']},c:{status:'open',blocked_by:['missing']}};assert.deepEqual(frontier(tickets),[]);assert.equal(isClear('',tickets),false);});
test('frontier is sorted and excludes claimed and out-of-scope dependencies',()=>{const tickets={b:{status:'open',blocked_by:[]},a:{status:'open',blocked_by:[]},c:{status:'open',blocked_by:['d']},d:{status:'out_of_scope',blocked_by:[]},e:{status:'open',claimed_by:'user',blocked_by:[]}};assert.deepEqual(frontier(tickets),['a','b']);});
test('clear requires all terminal tickets and no meaningful fog',()=>{const tickets={a:{status:'resolved'},b:{status:'out_of_scope'}};assert.equal(isClear('<!-- none -->\n',tickets),true);assert.equal(isClear('Unanswered adoption question',tickets),false);});
for(const input of [{available:false,evidence:null},{available:true,evidence:null},{available:true,evidence:'fact',blocked:true}])test('unpublished research failure/dependency stays open without claim/gist '+JSON.stringify(input),()=>assert.deepEqual(researchProposal(input),{status:'open',claimed_by:null,gist:null}));
test('unpublished observed research succeeds without persisted-ticket claim',()=>assert.deepEqual(researchProposal({available:true,evidence:'local source fact'}),{status:'resolved',claimed_by:null,gist:'local source fact'}));
test('prototype collision chooses fresh path without overwriting asset',()=>{const first=prototypePath(expl,'01-runtime.md');assert.equal(prototypePath(expl,'01-runtime.md',[first]),first.replace('.md','-1.md'));assert.throws(()=>prototypePath(expl,'../escape.md'));});
for(const type of ['grilling','prototype'])test('unavailable human input cannot resolve '+type,()=>{assert.throws(()=>assertUnresolvedHuman({type,hasAnswer:false,status:'resolved'}));assert.doesNotThrow(()=>assertUnresolvedHuman({type,hasAnswer:false,status:'claimed'}));});
test('failed claim/partial save never grants ownership or promises rollback',()=>{assert.throws(()=>verifyPartial({claimCommitted:false,workStarted:true,preserved:true,remaining:['claim']}));assert.equal(verifyPartial({claimCommitted:false,workStarted:false,preserved:true,remaining:['claim','resolution']}),true);assert.throws(()=>verifyPartial({claimCommitted:true,workStarted:true,preserved:false,remaining:['map']}));});
for(const bad of [ticketText().replace('status: open','status: open\nstatus: resolved'),ticketText().replace('type: task','type: invented'),ticketText().replace('blocked_by: []','blocked_by: [../outside.md]'),ticketText().replace('## Assets','## Resolution')])test('malformed ticket/frontmatter rejected '+bad.slice(0,35),()=>assert.throws(()=>parseMarkdown(bad,'ticket')));
test('oracle rejects broad claim that commits unrelated staged work',t=>{const p=workspace(t),s=setupExploration(p,'task');claim(p,{unrestricted:true});assert.throws(()=>verifyExploration(p,s,transcript('Done.')),/staged|unrelated/);});
test('oracle rejects fake resolution without any claim commit',t=>{const p=workspace(t),s=setupExploration(p,'task');fs.writeFileSync(p+'/'+ticket,fs.readFileSync(p+'/'+ticket,'utf8').replace('status: open','status: resolved'));assert.throws(()=>verifyExploration(p,s,transcript('Done.')),/claim commit/);});
test('oracle rejects claim that already performs work',t=>{const p=workspace(t),s=setupExploration(p,'task');const file=p+'/'+ticket;fs.writeFileSync(file,fs.readFileSync(file,'utf8').replace('status: open','status: claimed').replace('claimed_by:','claimed_by: agent-session').replace('<!-- Preserve resolution comment. -->','Already did work'));git(p,['commit','--only','-qm','Bad claim','--',ticket]);assert.throws(()=>verifyExploration(p,s,transcript('Done.')),/Claim already did work/);});
for(const mutation of ['second-ticket','existing-asset','false-clear','fake-fact','map-note','ticket-question'])test('oracle rejects '+mutation,t=>{const p=workspace(t),s=setupExploration(p,'task');resolveTask(p);const relative=mutation==='second-ticket'?second:mutation==='existing-asset'?expl+'/assets/existing.txt':mutation==='false-clear'||mutation==='map-note'?expl+'/map.md':ticket;let text=fs.readFileSync(p+'/'+relative,'utf8');text=mutation==='false-clear'?text.replace('status: resolving','status: clear'):mutation==='fake-fact'?text.replace(fact,'Node.js 99'):mutation==='map-note'?text.replace('Preserve this note.','Changed note.'):mutation==='ticket-question'?text.replace('Record the supported runtime','Change the selected question'):text+'bad';fs.writeFileSync(p+'/'+relative,text);assert.throws(()=>verifyExploration(p,s,transcript('Done.')));});
test('oracle rejects two human questions',t=>{const p=workspace(t),s=setupExploration(p,'hitl');claim(p);assert.throws(()=>verifyExploration(p,s,transcript(question+' Which other policy?')),/one human question/);});
test('oracle rejects fabricated research evidence',t=>{const p=workspace(t),s=setupExploration(p,'research-failure');claim(p);fs.writeFileSync(p+'/'+ticket,fs.readFileSync(p+'/'+ticket,'utf8').replace('status: claimed','status: resolved'));assert.throws(()=>verifyExploration(p,s,transcript('MISSING.md absent.')),/retain claim/);});
for(const mutation of ['claimed-proposal','fake-human','extra-file','wrong-link'])test('chart oracle rejects '+mutation,t=>{const p=workspace(t),s=setupExploration(p,'chart'),d=chart(p);if(mutation==='extra-file')write(p,d+'/unowned.txt','bad');else{const file=d+(mutation==='claimed-proposal'?'/tickets/01-runtime.md':mutation==='fake-human'?'/tickets/02-decision.md':'/map.md');let text=fs.readFileSync(p+'/'+file,'utf8');text=mutation==='claimed-proposal'?text.replace('claimed_by:','claimed_by: agent-session'):mutation==='fake-human'?text.replace('status: open','status: resolved'):text.replace('tickets/01-runtime.md','tickets/missing.md');fs.writeFileSync(p+'/'+file,text);}assert.throws(()=>verifyExploration(p,s,transcript('Done.')));});

test('oracle rejects changed local Git configuration',t=>{const p=workspace(t),s=setupExploration(p,'task');resolveTask(p);git(p,['config','commit.gpgsign','true']);assert.throws(()=>verifyExploration(p,s,transcript('Done.')),/configuration changed/);});

test('invalid dependencies prevent clear even on stored resolved tickets',()=>{assert.equal(isClear('',{a:{status:'resolved',blocked_by:['missing']}}),false);assert.equal(isClear('',{a:{status:'resolved',blocked_by:['b']},b:{status:'resolved',blocked_by:['a']}}),false);});
test('CRLF sections and quoted ownership scalars retain exact outside bytes',()=>{const original=ticketText().replaceAll('\n','\r\n'),claimed=original.replace('status: open','status: "claimed"').replace('claimed_by:','claimed_by: "agent-session"');assert.equal(parseMarkdown(original,'ticket').section('Question').trim(),'Record the supported runtime stated in FACTS.md.');assert.equal(preservedText(claimed,'ticket',{claim:true}),preservedText(original,'ticket',{claim:true}));});
for(const field of ['type','blocked_by','id','title','created'])test('oracle rejects unowned frontmatter change '+field,t=>{const p=workspace(t),s=setupExploration(p,'task');resolveTask(p);const relative=['type','blocked_by'].includes(field)?ticket:expl+'/map.md';let text=fs.readFileSync(p+'/'+relative,'utf8');text=text.replace(new RegExp('^'+field+':.*$','m'),field+': '+({type:'research',blocked_by:'["02-decision.md"]',id:'EXPL-bbbb',title:'Changed title',created:'"2026-02-02"'}[field]));fs.writeFileSync(p+'/'+relative,text);assert.throws(()=>verifyExploration(p,s,transcript('One task resolved.')),/Unowned/);});
for(const scenario of ['blocked','no-fog'])test('operational failure is not successful refusal '+scenario,t=>{const p=workspace(t),s=setupExploration(p,scenario);assert.throws(()=>verifyExploration(p,s,transcript('Parser unavailable; cannot inspect dependencies or continue with idd-quick-spec.')),e=>e.code==='HOST_BLOCKED');});

test('optional worker unavailability permits successful sequential chart',t=>{const p=workspace(t),s=setupExploration(p,'chart');chart(p);assert.equal(verifyExploration(p,s,transcript('Worker tools unavailable; completed the chart using sequential local research.')).outcome,'passed');});
test('expected missing source does not negate a completed research claim',t=>{const p=workspace(t),s=setupExploration(p,'research-failure');claim(p);assert.equal(verifyExploration(p,s,transcript('Git claim committed; required source MISSING.md was not found.')).outcome,'passed');});

test('self-answered rhetorical heading is not a second stakeholder question',t=>{const p=workspace(t),s=setupExploration(p,'hitl');claim(p);assert.equal(verifyExploration(p,s,transcript('**Did it work?** Yes.\n\n'+question)).outcome,'passed');});

test('unavailable or unauthorized tasks stay unresolved without invented outputs',()=>{for(const input of [{authorized:false,available:true},{authorized:true,available:false}]){assert.throws(()=>assertTaskScope({...input,status:'resolved'}));assert.doesNotThrow(()=>assertTaskScope({...input,status:'claimed'}));}assert.throws(()=>assertTaskScope({authorized:false,available:true,status:'claimed',outputs:['unapproved.md']}));});
