// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import YAML from 'yaml';
import {spawnSync} from 'node:child_process';
import {execute,runtimeVersion} from '../plugin/runtime/runner.mjs';
import {loadProfile,statusText} from '../plugin/runtime/profile.mjs';
import {snapshot} from '../plugin/runtime/snapshot.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),bundleRoot=path.join(root,'plugin/skills/idd-implement-spec');
const specFile='docs/specs/SPEC-c0de-greeting.yaml';
function fixture(t){const owned=fs.mkdtempSync(path.join(os.tmpdir(),'idd-runtime-test-')),project=path.join(owned,'project spaces');fs.cpSync(path.join(root,'tests/fixtures/installed-execution'),project,{recursive:true});for(const args of [['init','-q'],['add','.'],['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','-c','commit.gpgsign=false','commit','-qm','baseline']])assert.equal(spawnSync('git',args,{cwd:project}).status,0);fs.appendFileSync(path.join(project,'USER-NOTES.md'),'\nPreserve dirty notes.\n');t.after(()=>fs.rmSync(owned,{recursive:true,force:true}));return {project,specId:'SPEC-c0de',bundleRoot,environment:{},onAcknowledgment:()=>{}};}
function mutate(options,fn){const f=path.join(options.project,specFile),d=YAML.parse(fs.readFileSync(f,'utf8'));fn(d.spec);fs.writeFileSync(f,YAML.stringify(d));}
function report(spec){const labels=[...spec.expectations_detail.flatMap(e=>e.edge_cases.map((_,i)=>`${e.id} edge case ${i+1}`)),...spec.boundaries.map((_,i)=>`Boundary #${i+1}`),...spec.deliverables.map((_,i)=>`Deliverable #${i+1}`),...spec.validation.automated.map((_,i)=>`Automated check #${i+1}`)];return `## Header\nSPEC-c0de, 2026-09-13, simulated executor\n\n## Boundaries Acknowledged\n${spec.boundaries.join('\n')}\n\n## Self-Verification Table\n| Item | Status | Evidence |\n|---|---|---|\n${labels.map(l=>`| ${l} | pass | Simulated observed check |`).join('\n')}\n\n## Deliverables Produced\nsrc/greet.mjs, tests/greet.test.mjs, this report\n\n## spec_gaps_encountered\nNone.\n\n## Follow-Ups\nHuman review pending.\n`;}
function fake(options,{afterBuild,afterCheck,model='claude-opus-fixture',sonnet='claude-sonnet-fixture',afterPhase}={}) {
  let phaseIndex=0;
  return async (command,args)=> {
    const receipt={code:0,reason:null,signal:null,stdout:'',stderr:''};
    if(command!=='claude'){afterCheck?.();return receipt;}
    const phase=['orchestration','implementation','build'][phaseIndex++],id=args[args.indexOf(phase==='orchestration'?'--session-id':'--resume')+1];
    const s=YAML.parse(fs.readFileSync(path.join(options.project,specFile),'utf8')).spec;
    const selected=args.includes('--model')?args[args.indexOf('--model')+1]:model,actual=selected==='sonnet'?sonnet:selected;
    let text=phase==='build'?'Build completed.':`Boundaries Acknowledged — ${phase}\n`+s.boundaries.map((b,i)=>`${i+1}. ${b}${phase==='implementation'?'\nMeaning: Preserve this stated restriction.':''}`).join('\n');
    if(phase==='build'){fs.mkdirSync(path.join(options.project,'src'));fs.mkdirSync(path.join(options.project,'tests'));fs.writeFileSync(path.join(options.project,'src/greet.mjs'),'export const greet = name => name;\n');fs.writeFileSync(path.join(options.project,'tests/greet.test.mjs'),'// simulated\n');fs.writeFileSync(path.join(options.project,'docs/reviews/SPEC-c0de-20260913T120000Z-execution.md'),report(s));afterBuild?.();}
    afterPhase?.(phase);
    receipt.stdout=[{type:'system',subtype:'init',session_id:id,model:actual,output_style:'Fixture',tools:args[args.indexOf('--tools')+1].split(',')},{type:'assistant',message:{content:[{type:'text',text}]}},{type:'result',session_id:id,is_error:false,result:text}].map(e=>JSON.stringify(e)).join('\n');return receipt;
  };
}
async function simulation(t,options,behavior){const result=await execute({...options,run:fake(options,behavior)});if(result.evidence)t.after(()=>fs.rmSync(result.evidence,{recursive:true,force:true}));return result;}
test('installed descriptive-ID check is read-only, including dirty files',async t=>{const o=fixture(t),before=snapshot(o.project);const r=await execute({...o,check:true});assert.equal(r.outcome,'ready',r.error);assert.equal(r.hostInvocations,0);assert.deepEqual(snapshot(o.project),before);});
test('saved-session controller transitions only after simulated checks',async t=>{const o=fixture(t);const r=await simulation(t,o);assert.equal(r.outcome,'passed',r.error);assert.equal(r.hostInvocations,3);assert.equal(r.checks.length,1);assert.equal(YAML.parse(fs.readFileSync(path.join(o.project,specFile),'utf8')).spec.status,'review');});
for(const [name,change]of Object.entries({missing:s=>delete s.execution_contract,duplicate:s=>s.execution_contract.outputs[1].deliverable=1,traversal:s=>s.execution_contract.outputs[0].path='../escape',protected:s=>s.execution_contract.outputs[0].path='docs',overlap:s=>{s.execution_contract.outputs[0]={deliverable:1,path:'src',kind:'directory'};s.execution_contract.outputs[1].path='src/test.mjs';},approval:s=>s.peer_review.outcome='pending',warnings:s=>s.gap_check.status='warnings',status:s=>s.status='in-progress',unknown:s=>s.execution_contract.extra=true,command:s=>s.execution_contract.checks[0].argv=[],timeout:s=>s.execution_contract.checks[0].timeout_seconds=601}))test(`refuses ${name} before calls/writes`,async t=>{const o=fixture(t);mutate(o,change);const before=snapshot(o.project);const r=await execute({...o,run:()=>assert.fail('unexpected host')});assert.equal(r.outcome,'refused');assert.equal(r.hostInvocations,0);assert.deepEqual(snapshot(o.project),before);});
test('refuses duplicate YAML keys and ambiguous internal IDs',async t=>{const o=fixture(t),f=path.join(o.project,specFile),original=fs.readFileSync(f,'utf8');fs.writeFileSync(f,original.replace('  status: ready','  status: ready\n  status: review'));assert.equal((await execute({...o,check:true})).outcome,'refused');fs.writeFileSync(f,original);fs.copyFileSync(f,path.join(o.project,'docs/specs/copy.yaml'));assert.equal((await execute({...o,check:true})).outcome,'refused');});
test('refuses symlink output ancestor and dangling link',async t=>{const o=fixture(t);fs.symlinkSync('/tmp',path.join(o.project,'src'));assert.equal((await execute({...o,check:true})).outcome,'refused');fs.unlinkSync(path.join(o.project,'src'));fs.symlinkSync('/tmp/idd-missing-target-for-test',path.join(o.project,'src'));assert.equal((await execute({...o,check:true})).outcome,'refused');});
test('nested Claude refuses without changing guards',async t=>{const o=fixture(t),environment={CLAUDECODE:'1'};const r=await execute({...o,environment});assert.equal(r.outcome,'refused');assert.match(r.error,/Nested/);assert.equal(environment.CLAUDECODE,'1');});
test('status scalar preserves comments/quoting and refuses block form',()=>{for(const value of ['ready',"'ready'",'"ready"']){const before=`spec:\n  status: ${value} # keep\n  note: ready\n`;const after=statusText(before,'ready','in-progress');assert.equal(statusText(after,'in-progress','ready'),before);}assert.throws(()=>statusText('spec:\n  status: >-\n    ready\n','ready','in-progress'),/block-form/);});
for(const name of ['lifecycle','unowned','missing-row','blocker-gap','check-mutation','check-deletion','git-stage','bundle-target'])test(`preserves failure evidence: ${name}`,async t=>{const o=fixture(t);if(name==='bundle-target'){const copy=path.join(path.dirname(o.project),'bundle');fs.cpSync(bundleRoot,copy,{recursive:true});const link=copy+'-link';fs.symlinkSync(copy,link);o.bundleRoot=link;}
 const afterBuild=()=>{if(name==='lifecycle')mutate(o,s=>s.status='review');if(name==='unowned')fs.appendFileSync(path.join(o.project,'USER-NOTES.md'),'wrong');if(name==='git-stage')spawnSync('git',['add','src'],{cwd:o.project});if(name==='bundle-target')fs.appendFileSync(path.join(o.bundleRoot,'LICENSE'),'wrong');if(['missing-row','blocker-gap'].includes(name)){const f=path.join(o.project,'docs/reviews/SPEC-c0de-20260913T120000Z-execution.md');let text=fs.readFileSync(f,'utf8');text=name==='missing-row'?text.replace('| Boundary #1 | pass | Simulated observed check |',''):text.replace('None.','severity: "blocker-grade"');fs.writeFileSync(f,text);}};
 const afterCheck=()=>{if(name==='check-mutation')fs.appendFileSync(path.join(o.project,'src/greet.mjs'),'wrong');if(name==='check-deletion')fs.unlinkSync(path.join(o.project,'src/greet.mjs'));};const r=await simulation(t,o,{afterBuild,afterCheck});assert.equal(r.outcome,'failed',r.error);assert.ok(r.evidence);assert.notEqual(YAML.parse(fs.readFileSync(path.join(o.project,specFile),'utf8')).spec.status,name==='lifecycle'?'in-progress':'review');});
test('Sonnet policy checks actual resolved identity',async t=>{const o=fixture(t);o.implementerModel='sonnet';const r=await simulation(t,o,{sonnet:'claude-opus-wrong'});assert.equal(r.outcome,'failed');assert.equal(r.hostInvocations,2);assert.match(r.error,/Sonnet/);});
test('snapshot limits and runtime floor refuse',()=>{assert.throws(()=>runtimeVersion('22.19.9'),/22.20/);runtimeVersion('22.20.0');assert.throws(()=>snapshot(bundleRoot,{maxEntries:1}),/limit/);assert.throws(()=>snapshot(bundleRoot,{maxBytes:1}),/limit/);});

test('partial-name report parent directories are unowned',async t=>{const o=fixture(t);const r=await simulation(t,o,{afterBuild:()=>fs.mkdirSync(path.join(o.project,'docs/rev'))});assert.equal(r.outcome,'failed');assert.match(r.error,/unowned/);});

test('case aliases of protected paths and output overlaps refuse',async t=>{const o=fixture(t);mutate(o,s=>s.execution_contract.outputs[0].path='.GIT/config');assert.equal((await execute({...o,check:true})).outcome,'refused');mutate(o,s=>{s.execution_contract.outputs[0].path='Src/greet.mjs';s.execution_contract.outputs[1].path='src/greet.mjs';});assert.equal((await execute({...o,check:true})).outcome,'refused');});

test('transport forwards parent interruption and removes owned child',async t=>{
  const {spawn}=await import('node:child_process');const owned=fs.mkdtempSync(path.join(os.tmpdir(),'idd-signal-test-'));t.after(()=>fs.rmSync(owned,{recursive:true,force:true}));
  const pidFile=path.join(owned,'pid'),controller=path.join(owned,'controller.mjs');
  fs.writeFileSync(controller,`import {runHost} from ${JSON.stringify(new URL('../plugin/runtime/transport.mjs',import.meta.url).href)};const r=await runHost(process.execPath,['-e',${JSON.stringify("require('node:fs').writeFileSync("+JSON.stringify(pidFile)+",String(process.pid));setInterval(()=>{},1000)")}],{timeout:5000});console.log(JSON.stringify(r));`);
  const child=spawn(process.execPath,[controller],{stdio:['ignore','pipe','pipe']});let output='';child.stdout.on('data',b=>output+=b);const closed=new Promise(resolve=>child.on('close',resolve));
  const started=Date.now();while(!fs.existsSync(pidFile)&&Date.now()-started<3000)await new Promise(resolve=>setTimeout(resolve,20));assert.ok(fs.existsSync(pidFile),'Mock child started');const pid=Number(fs.readFileSync(pidFile,'utf8'));child.kill('SIGTERM');await closed;assert.equal(JSON.parse(output).reason,'interrupted');assert.throws(()=>process.kill(pid,0),/ESRCH/);
});

test('hardlinked lifecycle and output paths refuse before writes',async t=>{const o=fixture(t),file=path.join(o.project,specFile);fs.linkSync(file,path.join(o.project,'alias.txt'));const before=snapshot(o.project);const r=await execute({...o,check:true});assert.equal(r.outcome,'refused');assert.match(r.error,/Hardlink/);assert.deepEqual(snapshot(o.project),before);fs.unlinkSync(path.join(o.project,'alias.txt'));fs.mkdirSync(path.join(o.project,'src'));fs.linkSync(path.join(o.project,'USER-NOTES.md'),path.join(o.project,'src/greet.mjs'));assert.equal((await execute({...o,check:true})).outcome,'refused');});

test('validated gate bytes must match snapshot and current files',async t=>{const {bindGate}=await import('../plugin/runtime/runner.mjs');const o=fixture(t),p=loadProfile(o.project,o.specId,o.bundleRoot),before=snapshot(o.project,{excludeGit:true});bindGate(p,before,o.project);const gap=path.join(o.project,p.gapFile);fs.appendFileSync(gap,'\nConcurrent edit.\n');assert.throws(()=>bindGate(p,before,o.project),/Gate changed after/);assert.throws(()=>bindGate(p,snapshot(o.project,{excludeGit:true}),o.project),/Gate changed during/);});

test('nested transport cancellation lets inner controller terminate its child',async t=>{
  const {spawn}=await import('node:child_process');const owned=fs.mkdtempSync(path.join(os.tmpdir(),'idd-nested-signal-'));t.after(()=>fs.rmSync(owned,{recursive:true,force:true}));const pidFile=path.join(owned,'pid'),inner=path.join(owned,'inner.mjs'),outer=path.join(owned,'outer.mjs'),receipt=path.join(owned,'inner-result.json');
  const transport=new URL('../plugin/runtime/transport.mjs',import.meta.url).href;
  fs.writeFileSync(inner,`import fs from 'node:fs';import {runHost} from ${JSON.stringify(transport)};const r=await runHost(process.execPath,['-e',${JSON.stringify("require('node:fs').writeFileSync("+JSON.stringify(pidFile)+",String(process.pid));setInterval(()=>{},1000)")}],{timeout:5000});fs.writeFileSync(${JSON.stringify(receipt)},JSON.stringify(r));`);
  fs.writeFileSync(outer,`import {runHost} from ${JSON.stringify(transport)};console.log(JSON.stringify(await runHost(process.execPath,[${JSON.stringify(inner)}],{timeout:7000})));`);
  const child=spawn(process.execPath,[outer],{stdio:['ignore','pipe','pipe']});let output='';child.stdout.on('data',b=>output+=b);const closed=new Promise(resolve=>child.on('close',resolve));const start=Date.now();while(!fs.existsSync(pidFile)&&Date.now()-start<3000)await new Promise(resolve=>setTimeout(resolve,20));assert.ok(fs.existsSync(pidFile));const pid=Number(fs.readFileSync(pidFile));child.kill('SIGTERM');await closed;assert.equal(JSON.parse(output).reason,'interrupted');assert.equal(JSON.parse(fs.readFileSync(receipt)).reason,'interrupted');assert.throws(()=>process.kill(pid,0),/ESRCH/);
});

test('prototype-like filenames are preserved as ordinary unowned paths',async t=>{const o=fixture(t);const r=await simulation(t,o,{afterBuild:()=>fs.writeFileSync(path.join(o.project,'__proto__'),'unowned')});assert.equal(r.outcome,'failed');assert.match(r.error,/unowned/);});
test('nonzero independent command leaves in-progress and evidence',async t=>{const o=fixture(t),run=fake(o);const r=await execute({...o,run:async(c,a,opts)=>c==='claude'?run(c,a,opts):{code:1,reason:null,signal:null,stdout:'',stderr:'Deliberate failed check'}});if(r.evidence)t.after(()=>fs.rmSync(r.evidence,{recursive:true,force:true}));assert.equal(r.outcome,'failed');assert.match(r.error,/verification failed/);assert.equal(YAML.parse(fs.readFileSync(path.join(o.project,specFile),'utf8')).spec.status,'in-progress');});
