// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import {workspace,root,write} from './helpers/workspace.mjs';import {validateNativeDistribution,validatePlugin} from '../scripts/lib/packages.mjs';
import {nativeFixture,containedNative,verifyNativeConsumer,packageSnapshot,verifyNativeCache,nativeCommand} from './helpers/native-distribution.mjs';
import {snapshot} from '../plugin/runtime/snapshot.mjs';
function fixture(t){const d=workspace(t);for(const p of ['plugin','tests/fixtures/plugin-inventory.json','.agents/plugins/marketplace.json','.claude-plugin/marketplace.json']){const to=path.join(d,p);fs.mkdirSync(path.dirname(to),{recursive:true});fs.cpSync(path.join(root,p),to,{recursive:true});}return d;}
function change(dir,file,mutate){const p=path.join(dir,file),d=JSON.parse(fs.readFileSync(p));mutate(d);fs.writeFileSync(p,JSON.stringify(d,null,2)+'\n');}
test('native package uses distinct portable/compat schemas and repository-root catalogs',()=>{const r=validateNativeDistribution(root);assert.equal(r.skills,16);assert.equal(r.pluginRoot,path.join(root,'plugin'));validatePlugin(root);});
for(const [name,file,mutate]of [
  ['missing schema','plugin/plugin.json',d=>delete d.$schema],['wrong schema','plugin/plugin.json',d=>d.$schema='https://example.invalid/schema'],
  ...['skills','interface','userConfig','hooks','apps','mcpServers'].map(k=>['undeclared '+k,'plugin/plugin.json',d=>d[k]={}]),
  ['identity','plugin/plugin.json',d=>d.name='wrong'],['version','plugin/plugin.json',d=>d.version='9.9.9'],['compat conflict','plugin/.codex-plugin/plugin.json',d=>d.description='conflicting'],
  ['legacy skills override','plugin/.codex-plugin/plugin.json',d=>d.skills='../outside'],['wrong capabilities','plugin/.codex-plugin/plugin.json',d=>d.interface.capabilities=['Network']],
  ['wrong policy','.agents/plugins/marketplace.json',d=>d.plugins[0].policy.installation='AUTO'],['wrong auth','.agents/plugins/marketplace.json',d=>d.plugins[0].policy.authentication='NEVER'],
  ['escaped Codex source','.agents/plugins/marketplace.json',d=>d.plugins[0].source.path='../plugin'],['absolute Codex source','.agents/plugins/marketplace.json',d=>d.plugins[0].source.path='/tmp/plugin'],
  ['escaped Claude source','.claude-plugin/marketplace.json',d=>d.plugins[0].source='../plugin'],['wrong marketplace name','.claude-plugin/marketplace.json',d=>d.name='external'],
])test('native validation refuses '+name+' without writes',t=>{const d=fixture(t);change(d,file,mutate);const before=snapshot(d);assert.throws(()=>validateNativeDistribution(d));assert.deepEqual(snapshot(d),before);});
for(const kind of ['missing','symlink','file'])test('fixed native skills target rejects '+kind,t=>{const d=fixture(t),p=path.join(d,'plugin/skills'),elsewhere=path.join(d,'other');fs.renameSync(p,elsewhere);if(kind==='symlink')fs.symlinkSync(elsewhere,p);if(kind==='file')fs.writeFileSync(p,'not a directory');assert.throws(()=>validateNativeDistribution(d));});
test('native fixed discovery rejects missing public entry and extra skill',t=>{const d=fixture(t),p=path.join(d,'plugin/skills/idd-interview/SKILL.md'),text=fs.readFileSync(p);fs.unlinkSync(p);assert.throws(()=>validateNativeDistribution(d));fs.writeFileSync(p,text);write(d,'plugin/skills/unlisted/SKILL.md','unlisted');assert.throws(()=>validateNativeDistribution(d),/inventory/);});
test('marketplace and compatibility manifest symlinks refuse',t=>{const d=fixture(t);for(const p of ['.agents/plugins/marketplace.json','plugin/.codex-plugin/plugin.json']){const file=path.join(d,p),backup=file+'.saved';fs.renameSync(file,backup);fs.symlinkSync(backup,file);assert.throws(()=>validateNativeDistribution(d),/SYMLINK/);fs.unlinkSync(file);fs.renameSync(backup,file);}});
test('isolated native fixture neither inherits credentials nor edits parent environment',t=>{const d=workspace(t),before={...process.env},s=nativeFixture(d,'codex');assert.deepEqual({...process.env},before);for(const key of ['CODEX_HOME','CLAUDE_CONFIG_DIR','XDG_CONFIG_HOME','XDG_CACHE_HOME','XDG_STATE_HOME'])assert.ok(s.environment[key].startsWith(d+path.sep));assert.equal(s.environment.HOME,undefined);for(const key of ['ANTHROPIC_API_KEY','OPENAI_API_KEY','CODEX_API_KEY','CLAUDE_CODE_OAUTH_TOKEN'])assert.equal(s.environment[key],undefined);assert.equal(s.environment.GIT_CONFIG_NOSYSTEM,'1');assert.equal(fs.readFileSync(s.environment.GIT_CONFIG_GLOBAL,'utf8'),'');});
test('native path and cache checks reject escape and root links',t=>{const d=workspace(t),s=nativeFixture(d,'codex'),cache=path.join(s.client,'cache');fs.cpSync(path.join(s.source,'plugin'),cache,{recursive:true});const before=packageSnapshot(cache);verifyNativeCache(s,cache,before);assert.throws(()=>containedNative(s.client,s.source),/escaped/);const moved=cache+'-moved';fs.renameSync(cache,moved);fs.symlinkSync(moved,cache);assert.throws(()=>verifyNativeCache(s,cache,before),/directory/);});
test('native consumer guards permit selected settings only and detect unrelated changes',t=>{const d=workspace(t),s=nativeFixture(d,'claude');write(s.project,'.claude/settings.json','{}');verifyNativeConsumer(s);fs.appendFileSync(path.join(s.project,'USER-NOTES.md'),'changed');assert.throws(()=>verifyNativeConsumer(s),/consumer/);});
test('native consumer guard rejects new hierarchy or settings symlink',t=>{const d=workspace(t),s=nativeFixture(d,'claude');fs.mkdirSync(path.join(s.project,'docs'));assert.throws(()=>verifyNativeConsumer(s),/addition/);fs.rmdirSync(path.join(s.project,'docs'));fs.mkdirSync(path.join(s.project,'.claude'));fs.symlinkSync(path.join(s.project,'USER-NOTES.md'),path.join(s.project,'.claude/settings.json'));assert.throws(()=>verifyNativeConsumer(s));});
test('native command receives isolated env and persists failure receipt',async t=>{const d=workspace(t),s=nativeFixture(d,'codex');const r=await nativeCommand(s,['-e','console.log(JSON.stringify({home:process.env.CODEX_HOME,key:process.env.OPENAI_API_KEY}));process.stderr.write("fixture failure");process.exit(7)'],{command:process.execPath,allowFailure:true});assert.equal(r.code,7);assert.deepEqual(JSON.parse(r.stdout),{home:s.environment.CODEX_HOME});const records=JSON.parse(fs.readFileSync(path.join(d,'receipts.json')));assert.equal(records.length,1);assert.equal(records[0].code,7);assert.equal(records[0].stderr,'fixture failure');});
test('native total deadline refuses before an additional command',async t=>{const s=nativeFixture(workspace(t),'codex');s.started=Date.now()-600001;await assert.rejects(nativeCommand(s,['--version']),/budget/);assert.equal(s.receipts.length,0);});
test('native settings guard protects unrelated registration throughout IDD changes',t=>{const s=nativeFixture(workspace(t),'claude');s.unrelatedSettings={enabledPlugins:{'unrelated@market':true},extraKnownMarketplaces:{market:{source:{source:'directory',path:s.retained}}}};const current=structuredClone(s.unrelatedSettings);current.enabledPlugins['idd-framework@idd-framework-local']=true;write(s.project,'.claude/settings.json',JSON.stringify(current));verifyNativeConsumer(s);current.enabledPlugins['unrelated@market']=false;write(s.project,'.claude/settings.json',JSON.stringify(current));assert.throws(()=>verifyNativeConsumer(s),/Unrelated project/);});
test('native consumer guard rejects a symlinked Claude settings directory',t=>{const s=nativeFixture(workspace(t),'claude');fs.symlinkSync(s.client,path.join(s.project,'.claude'));assert.throws(()=>verifyNativeConsumer(s),/settings root/);});
