// SPDX-License-Identifier: Apache-2.0
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import YAML from 'yaml';
import {workspace,root,write} from './helpers/workspace.mjs';
import {snapshot,gitState,hash} from '../plugin/runtime/snapshot.mjs';
import {execute,workflowEntry} from '../plugin/runtime/runner.mjs';
import {runProcess} from '../scripts/lib/process.mjs';
import {assemble} from '../scripts/build-skills.mjs';
import {catalog,verifyClosure,routerPrompt,verifyRouting,verifySelectedRemoval,installedSnapshot,installerReceipt,refreshMarker} from './helpers/router-distribution.mjs';
import {parseRouterOptions} from '../scripts/evaluate-router.mjs';
const router=path.join(root,'plugin/skills/idd-orchestration');
test('router has exactly15 closed stages and16 public entries, with no nested skills',()=>{assert.equal(catalog.stages.length,15);assert.equal(catalog.bundles.length,16);assert.ok(catalog.bundles.every(b=>b.profile==='portable'));verifyClosure(router);const text=fs.readFileSync(path.join(router,'SKILL.md'),'utf8');for(const b of catalog.bundles.filter(b=>b.directory!=='idd-orchestration'))assert.ok(text.includes(`stages/${b.directory.slice(4)}/workflow.md`));});
test('router aliases preserve six paths using the reviewed portable sources',()=>{const b=catalog.bundles.find(b=>b.directory==='idd-orchestration'),aliases={'expectation-template':'authoring/expectation-template','exploration-template':'exploration/format','intention-template':'authoring/intention-template','ledger-reference':'archive/ledger','product-template':'pilot/product-template','spec-reference':'pilot/spec-reference'};for(const [name,source]of Object.entries(aliases)){assert.equal(b.files.find(f=>f.destination===`references/${name}.md`).source,`plugin/references/${source}.md`);assert.deepEqual(fs.readFileSync(path.join(router,`references/${name}.md`)),fs.readFileSync(path.join(root,`plugin/references/${source}.md`)));}});
test('one canonical edit updates direct and routed copies; stale/extra copies refuse',t=>{const dir=workspace(t);const source='plugin/references/guide.md';write(dir,source,'Original shared resource\n');write(dir,'plugin/workflows/direct.md','---\nname: idd-direct\ndescription: Fixture\n---\n');write(dir,'plugin/workflows/router.md','---\nname: idd-router\ndescription: Fixture\n---\n');const c={schemaVersion:1,stages:[],bundles:[{directory:'idd-direct',profile:'portable',files:[{source:'plugin/workflows/direct.md',destination:'SKILL.md',executable:false},{source,destination:'references/guide.md',executable:false}]},{directory:'idd-router',profile:'portable',files:[{source:'plugin/workflows/router.md',destination:'SKILL.md',executable:false},{source:'plugin/workflows/direct.md',destination:'stages/direct/workflow.md',executable:false},{source,destination:'stages/direct/references/guide.md',executable:false}]}]};assemble(dir,{catalog:c});assert.equal(assemble(dir,{catalog:c}).changed,0);fs.appendFileSync(path.join(dir,source),'Changed\n');assert.throws(()=>assemble(dir,{catalog:c,check:true}),/STALE/);assemble(dir,{catalog:c});for(const p of ['idd-direct/references/guide.md','idd-router/stages/direct/references/guide.md'])assert.match(fs.readFileSync(path.join(dir,'plugin/skills',p),'utf8'),/Changed/);write(dir,'plugin/skills/idd-router/unowned.md','Keep');const before=snapshot(dir);assert.throws(()=>assemble(dir,{catalog:c}),/EXTRA/);assert.deepEqual(snapshot(dir),before);});
function executionFixture(t,layout){const owned=workspace(t),project=path.join(owned,'project'),bundle=path.join(owned,'bundle');fs.cpSync(path.join(root,'tests/fixtures/installed-execution'),project,{recursive:true});fs.cpSync(layout==='routed'?path.join(router,'stages/implement-spec'):path.join(root,'plugin/skills/idd-implement-spec'),bundle,{recursive:true});for(const args of [['init','-q'],['add','.'],['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','-c','commit.gpgsign=false','commit','-qm','baseline']])runProcess('git',args,{cwd:project});fs.appendFileSync(path.join(project,'USER-NOTES.md'),'\nUnrelated dirty bytes.\n');return {project,bundleRoot:bundle,specId:'SPEC-c0de',environment:{},onAcknowledgment:()=>{}};}
function syntheticReport(s){const labels=[...s.expectations_detail.flatMap(e=>e.edge_cases.map((_,i)=>`${e.id} edge case ${i+1}`)),...s.boundaries.map((_,i)=>`Boundary #${i+1}`),...s.deliverables.map((_,i)=>`Deliverable #${i+1}`),...s.validation.automated.map((_,i)=>`Automated check #${i+1}`)];return `## Header\nSPEC-c0de, 2026-09-13, synthetic protocol fixture\n\n## Boundaries Acknowledged\n${s.boundaries.join('\n')}\n\n## Self-Verification Table\n| Item | Status | Evidence |\n|---|---|---|\n${labels.map(l=>`| ${l} | pass | Synthetic protocol only |`).join('\n')}\n\n## Deliverables Produced\nFixture files and report.\n\n## spec_gaps_encountered\nNone.\n\n## Follow-Ups\nActual model behavior requires separate observation.\n`;}
for(const layout of ['direct','routed'])test(`complete guarded protocol resolves every ${layout} handoff and preserves policy`,async t=>{const options=executionFixture(t,layout),before=snapshot(options.project,{excludeGit:true});let calls=0;const seen=[];const result=await execute({...options,run:async(command,args,opts)=>{if(command!=='claude')return {code:0,reason:null,stdout:'synthetic check',stderr:''};const phase=['orchestration','implementation','build'][calls++],entry=opts.input.match(/Read the installed workflow at (.*?) and required references\./)?.[1];assert.equal(entry,path.join(fs.realpathSync(options.bundleRoot),layout==='direct'?'SKILL.md':'workflow.md'));assert.ok(fs.statSync(entry).isFile());seen.push(entry);const s=YAML.parse(fs.readFileSync(path.join(options.project,'docs/specs/SPEC-c0de-greeting.yaml'),'utf8')).spec;assert.equal(s.status,phase==='orchestration'?'ready':'in-progress');assert.equal(args.includes('--model'),phase!=='orchestration');const session=args[args.indexOf(phase==='orchestration'?'--session-id':'--resume')+1];let text=`Boundaries Acknowledged — ${phase}\n`+s.boundaries.map((b,i)=>`${i+1}. ${b}${phase==='implementation'?'\nMeaning: Preserve this restriction.':''}`).join('\n');if(phase==='build'){write(options.project,'src/greet.mjs','// Synthetic protocol output\n');write(options.project,'tests/greet.test.mjs','// Synthetic protocol test\n');write(options.project,'docs/reviews/SPEC-c0de-20260913T120000Z-execution.md',syntheticReport(s));text='Build complete.';}return {code:0,reason:null,stderr:'',stdout:[{type:'system',subtype:'init',session_id:session,model:'claude-opus-fixture',output_style:'Fixture',tools:args[args.indexOf('--tools')+1].split(',')},{type:'assistant',message:{content:[{type:'text',text}]}},{type:'result',session_id:session,is_error:false,result:text}].map(JSON.stringify).join('\n')};}});if(result.evidence)t.after(()=>fs.rmSync(result.evidence,{recursive:true,force:true}));assert.equal(result.outcome,'passed',result.error);assert.equal(seen.length,3);assert.equal(result.checks.length,1);assert.equal(new Set(result.phases.map(p=>p.observed.sessionId)).size,1);assert.equal(YAML.parse(fs.readFileSync(path.join(options.project,'docs/specs/SPEC-c0de-greeting.yaml'),'utf8')).spec.status,'review');assert.deepEqual(snapshot(options.project,{excludeGit:true}).entries['USER-NOTES.md'],before.entries['USER-NOTES.md']);});
for(const kind of ['missing','symlink','dangling','hardlink','directory','unsafe-preferred'])test(`unsafe ${kind} entry refuses before calls and project changes`,async t=>{const o=executionFixture(t,'routed'),entry=path.join(o.bundleRoot,'workflow.md');fs.unlinkSync(entry);if(kind==='symlink'||kind==='dangling')fs.symlinkSync(path.join(o.project,kind==='symlink'?'USER-NOTES.md':'absent'),entry);if(kind==='hardlink')fs.linkSync(path.join(o.project,'USER-NOTES.md'),entry);if(kind==='directory')fs.mkdirSync(entry);if(kind==='unsafe-preferred'){fs.writeFileSync(entry,'safe fallback');fs.symlinkSync(entry,path.join(o.bundleRoot,'SKILL.md'));}const before=snapshot(o.project,{excludeGit:true}),bundle=snapshot(o.bundleRoot);const r=await execute({...o,run:()=>assert.fail('Host called')});assert.equal(r.outcome,'refused');assert.equal(r.hostInvocations,0);assert.deepEqual(snapshot(o.project,{excludeGit:true}),before);assert.deepEqual(snapshot(o.bundleRoot),bundle);});
test('entry resolver prefers safe SKILL.md when both exist',t=>{const d=workspace(t);write(d,'workflow.md','routed');write(d,'SKILL.md','direct');assert.equal(workflowEntry(d),path.join(d,'SKILL.md'));});
test('route prompts retain explicit stops and source-removal conditions',()=>{assert.match(routerPrompt('outcomes','/tmp/SKILL.md'),/stop before stakeholder/);assert.match(routerPrompt('missing','/tmp/SKILL.md'),/SPEC-dead/);assert.throws(()=>routerPrompt('unknown','/tmp'));});
test('evaluator validates options before fixture/model work',()=>{assert.deepEqual(parseRouterOptions(['--host','claude','--scenario','controller']),{host:'claude',scenario:'controller'});for(const args of [['--host','codex','--scenario','controller'],['--host','claude','--scenario','missing','--default-mode'],['--host','claude','--host','codex'],['--host','invalid','--scenario','outcomes']])assert.throws(()=>parseRouterOptions(args));});
test('routing preservation oracle rejects write despite convincing final text',t=>{const o=executionFixture(t,'routed'),state={project:o.project,before:snapshot(o.project,{excludeGit:true}),git:gitState(fs.realpathSync(o.project)),config:hash(fs.readFileSync(path.join(o.project,'.git/config')))};write(o.project,'scratch.md','unauthorized');assert.throws(()=>verifyRouting(state,'missing','SPEC-dead is missing'),/Routing changed/);});
test('selected removal distinguishes exact shared retention from actual removal',t=>{const d=workspace(t),p=write(d,'.agents/skills/idd-test/SKILL.md','retained'),before=installedSnapshot(d,path.dirname(p));assert.equal(verifySelectedRemoval(d,'codex','idd-test',before).state,'still-installed');fs.appendFileSync(p,'changed');assert.throws(()=>verifySelectedRemoval(d,'codex','idd-test',before),/Retained shared installation changed/);fs.rmSync(path.dirname(p),{recursive:true});assert.equal(verifySelectedRemoval(d,'codex','idd-test',before).state,'removed');});
test('retained canonical copy cannot hide an unremoved Claude alias',t=>{const d=workspace(t),p=write(d,'.agents/skills/idd-test/SKILL.md','retained'),before=installedSnapshot(d,path.dirname(p));write(d,'.claude/skills/idd-test/SKILL.md','still active');assert.throws(()=>verifySelectedRemoval(d,'claude','idd-test',before),/Claude alias/);fs.rmSync(path.join(d,'.claude/skills/idd-test'),{recursive:true});assert.equal(verifySelectedRemoval(d,'claude','idd-test',before).state,'still-installed');});
for(const file of ['SKILL.md','LICENSE','references/spec-reference.md'])test('bundle closure rejects altered root '+file,t=>{const d=workspace(t);fs.cpSync(router,d,{recursive:true});fs.appendFileSync(path.join(d,file),'corrupt');assert.throws(()=>verifyClosure(d),/Mapped bytes/);});
test('refresh allows only exact original plus marker, and closure rejects extra directory',t=>{const d=workspace(t);fs.cpSync(router,d,{recursive:true});fs.appendFileSync(path.join(d,'SKILL.md'),refreshMarker);verifyClosure(d,undefined,{refreshed:true});fs.mkdirSync(path.join(d,'unexpected'));assert.throws(()=>verifyClosure(d,undefined,{refreshed:true}),/membership/);fs.rmdirSync(path.join(d,'unexpected'));fs.writeFileSync(path.join(d,'SKILL.md'),'garbled'+refreshMarker);assert.throws(()=>verifyClosure(d,undefined,{refreshed:true}),/Mapped bytes/);});
test('removal rejects dangling aliases and same-content canonical symlink replacements',t=>{const d=workspace(t),canonical=path.join(d,'.agents/skills/idd-test');write(canonical,'SKILL.md','retained');const before=installedSnapshot(d,canonical);fs.mkdirSync(path.join(d,'.claude/skills'),{recursive:true});const alias=path.join(d,'.claude/skills/idd-test');fs.symlinkSync('/nonexistent-fixture',alias);assert.throws(()=>verifySelectedRemoval(d,'claude','idd-test',before),/Claude alias/);fs.unlinkSync(alias);const moved=path.join(d,'moved');fs.renameSync(canonical,moved);fs.symlinkSync(moved,canonical);assert.throws(()=>verifySelectedRemoval(d,'codex','idd-test',before),/canonical root/);});
test('failed installer operation retains full argv/output/termination before throwing',t=>{const d=workspace(t),receipts=[],run=()=>({status:null,signal:'SIGKILL',error:new Error('ETIMEDOUT'),stdout:'partial output',stderr:'diagnostic'});assert.throws(()=>installerReceipt(d,d,['remove','idd-test','--agent','codex','--yes'],receipts,{run}),/Installer failed/);const r=JSON.parse(fs.readFileSync(path.join(d,'receipts.json')))[0];assert.ok(r.args.includes('idd-test'));assert.equal(r.signal,'SIGKILL');assert.equal(r.error,'ETIMEDOUT');assert.equal(r.stdout,'partial output');assert.equal(r.stderr,'diagnostic');});
